provider=openai_compatible
base_url=https://api.together.xyz
model=meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo
api_key=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
